# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190603_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neigborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='neighbors.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
