# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190603_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neigborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='neighbors.Neighborhood'),
        ),
    ]
